---
기본 구조 선언

In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

---
데이터세트, 데이터로더 선언

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

---
모델, 오차함수, optimizer 선언

In [3]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

---
학습

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.1948, 0.5150],
        [1.0149, 0.2495]], requires_grad=True), Parameter containing:
tensor([-0.5127,  0.1006], requires_grad=True)], Cost : 0.065
Epoch : 2000, Model : [Parameter containing:
tensor([[0.3881, 0.4148],
        [1.0510, 0.2308]], requires_grad=True), Parameter containing:
tensor([-0.8062,  0.0457], requires_grad=True)], Cost : 0.017
Epoch : 3000, Model : [Parameter containing:
tensor([[0.4867, 0.3639],
        [1.0695, 0.2213]], requires_grad=True), Parameter containing:
tensor([-0.9557,  0.0177], requires_grad=True)], Cost : 0.004
Epoch : 4000, Model : [Parameter containing:
tensor([[0.5369, 0.3379],
        [1.0789, 0.2164]], requires_grad=True), Parameter containing:
tensor([-1.0319,  0.0034], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[0.5624, 0.3247],
        [1.0837, 0.2139]], requires_grad=True), Parameter containing:
tensor([-1.0707, -0.0038], requires_grad=True)]

---
편향 제거(bias 제거인듯)

In [5]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [6]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.4826, 0.1844],
        [0.9041, 0.3584]], requires_grad=True)], Cost : 0.096
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.7326, -0.0175],
        [ 0.9443,  0.3259]], requires_grad=True)], Cost : 0.062
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9311, -0.1782],
        [ 0.9762,  0.3001]], requires_grad=True)], Cost : 0.039
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.0889, -0.3058],
        [ 1.0016,  0.2795]], requires_grad=True)], Cost : 0.024
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.2143, -0.4072],
        [ 1.0218,  0.2632]], requires_grad=True)], Cost : 0.016
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.3140, -0.4878],
        [ 1.0379,  0.2502]], requires_grad=True)], Cost : 0.010
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.3932, -0.5519],
        [ 1.0506,  0.2399]], requires_grad=True)], Cost : 0.006
Epoch : 8000, Model : [Parameter containing:
