텐서 생성

In [7]:
import torch

print(torch.tensor([1, 2, 3]))
print(torch.Tensor([[1, 2, 3], [4, 5, 6]]))
print(torch.LongTensor([1, 2, 3]))
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


---
텐서 속성 출력

In [ ]:
import torch

tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.2764, 0.0040]])
torch.Size([1, 2])
torch.float32
cpu


---
텐서 차원 변환

In [4]:
import torch

tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)

tensor([[0.3509, 0.0411]])
torch.Size([1, 2])


In [5]:
tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape)

tensor([[0.3509],
        [0.0411]])
torch.Size([2, 1])


---
텐서 자료형 설정

In [6]:
import torch


tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)

tensor([[0.6613, 0.5183, 0.4572],
        [0.1428, 0.0576, 0.1588],
        [0.5456, 0.7763, 0.0702]])


---
텐서 GPU 장치 설정

In [9]:
import torch


device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
print(gpu)
print(tensor)

cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.6916]], device='cuda:0')


---
텐서 장치 변환

In [10]:
import torch


cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to("cuda")
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


---
넘파이 배열을 텐서로 변환

In [1]:
import torch
import numpy as np

ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


---
텐서를 넘파이 배열로 변환

In [2]:
import torch


tensor = torch.cuda.FloatTensor([1, 2, 3])
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
