의존성 설치 중 gensim 라이브러리 설치 오류

In [ ]:
pip install --use-pep517 gensim

fastAPI 버전 다운

In [ ]:
pip install -r requirements.txt

텐서

In [18]:
import torch

print(torch.tensor([1, 2, 3]))
print(torch.tensor([[1, 2, 3], [4, 5,6]]))
print(torch.LongTensor([1, 2, 3]))
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


In [ ]:
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape) 

tensor([[0.2255, 0.4549]])
torch.Size([1, 2])
tensor([[0.2255],
        [0.4549]])
torch.Size([2, 1])


In [28]:
import numpy as np

ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


In [29]:
tensor = torch.FloatTensor([1, 2, 3])
ndarray = tensor.detach().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
